import type { Metadata } from "next";

export const metadata: Metadata = {
  "title": "Baby & Parenting Calculators – 8 Free Tools 2025 | CalcDigi",
  "description": "8 free baby and parenting calculators — due date, baby weight percentile, feeding amounts, diaper costs, sleep schedule, child height predictor, childcare costs, and baby name popularity.",
  "openGraph": {
    "title": "Baby & Parenting Calculators – 8 Free Tools 2025 | CalcDigi",
    "description": "8 free baby and parenting calculators — due date, baby weight percentile, feeding amounts, diaper costs, sleep schedule, child height predictor, childcare costs, and baby name popularity.",
    "type": "website"
  },
  "alternates": {
    "canonical": "/pages/baby"
  }
};

export default function Page() {
  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: "\n.cat-hero{padding:56px 0 40px;text-align:center;background:linear-gradient(135deg,var(--c-bg) 0%,var(--c-rule2) 100%);}\n.cat-hero h1{font-size:clamp(2rem,5vw,3rem);margin:12px 0;}\n.cat-badge{display:inline-flex;align-items:center;gap:8px;background:var(--c-accent);color:#fff;padding:6px 16px;border-radius:100px;font-size:13px;font-weight:600;margin-bottom:16px;}\n.cat-sub{color:var(--c-ink2);font-size:1.05rem;max-width:600px;margin:0 auto 28px;}\n.stats{display:flex;justify-content:center;gap:32px;margin-top:24px;}\n.stat{text-align:center;}\n.stat-n{font-size:1.8rem;font-weight:700;color:var(--c-accent);font-family:var(--f-serif);}\n.stat-l{font-size:12px;color:var(--c-ink2);text-transform:uppercase;letter-spacing:.05em;}\n.calc-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:16px;margin-top:32px;}\n.calc-card{display:flex;flex-direction:column;align-items:center;text-align:center;padding:24px 16px;background:var(--c-bg);border:1.5px solid var(--c-rule);border-radius:16px;text-decoration:none;color:var(--c-ink);transition:all .2s;}\n.calc-card:hover{border-color:var(--c-accent);transform:translateY(-2px);box-shadow:0 8px 24px rgba(0,0,0,.08);}\n.calc-card-icon{font-size:2rem;margin-bottom:12px;}\n.calc-card-name{font-size:14px;font-weight:500;line-height:1.4;}\n" }} />
      <div dangerouslySetInnerHTML={{ __html: "<main>\n<section class=\"cat-hero\">\n  <div class=\"container\">\n    <nav class=\"calc-breadcrumb\" style=\"justify-content:center;margin-bottom:20px;\">\n      <a href=\"/\">Home</a><span class=\"bc-sep\"> / </span><span>Baby &amp; Parenting Calculators</span>\n    </nav>\n    <div class=\"cat-badge\">👶 8 Free Calculators · AI-Powered · No Sign-Up</div>\n    <h1>Baby &amp; Parenting<br><em>Calculators</em></h1>\n    <p class=\"cat-sub\">Free tools for new and expecting parents — due dates, baby growth percentiles, feeding amounts, sleep schedules, childcare costs, and more. Powered by AI insights.</p>\n    <div class=\"stats\">\n      <div class=\"stat\"><div class=\"stat-n\">8</div><div class=\"stat-l\">Calculators</div></div>\n      <div class=\"stat\"><div class=\"stat-n\">100%</div><div class=\"stat-l\">Free</div></div>\n      <div class=\"stat\"><div class=\"stat-n\">AI</div><div class=\"stat-l\">Insights</div></div>\n      <div class=\"stat\"><div class=\"stat-n\">0</div><div class=\"stat-l\">Sign-Up</div></div>\n    </div>\n  </div>\n</section>\n<section class=\"section\">\n  <div class=\"container\">\n    <h2 style=\"font-size:1.5rem;font-weight:700;margin-bottom:8px;\">All Baby &amp; Parenting Calculators</h2>\n    <p style=\"color:var(--c-ink2);margin-bottom:32px;\">Click any calculator to get started — no registration required.</p>\n    <div class=\"calc-grid\">\n      <a href=\"/calculators/baby/due-date-calculator\" class=\"calc-card\"><div class=\"calc-card-icon\">🤰</div><div class=\"calc-card-name\">Due Date Calculator</div></a>\n      <a href=\"/calculators/baby/baby-weight-percentile-calculator\" class=\"calc-card\"><div class=\"calc-card-icon\">⚖️</div><div class=\"calc-card-name\">Baby Weight Percentile</div></a>\n      <a href=\"/calculators/baby/baby-feeding-calculator\" class=\"calc-card\"><div class=\"calc-card-icon\">🍼</div><div class=\"calc-card-name\">Baby Feeding Calculator</div></a>\n      <a href=\"/calculators/baby/diaper-cost-calculator\" class=\"calc-card\"><div class=\"calc-card-icon\">💰</div><div class=\"calc-card-name\">Diaper Cost Calculator</div></a>\n      <a href=\"/calculators/baby/baby-sleep-calculator\" class=\"calc-card\"><div class=\"calc-card-icon\">😴</div><div class=\"calc-card-name\">Baby Sleep Calculator</div></a>\n      <a href=\"/calculators/baby/child-height-predictor-calculator\" class=\"calc-card\"><div class=\"calc-card-icon\">📏</div><div class=\"calc-card-name\">Child Height Predictor</div></a>\n      <a href=\"/calculators/baby/childcare-cost-calculator\" class=\"calc-card\"><div class=\"calc-card-icon\">🏠</div><div class=\"calc-card-name\">Childcare Cost Calculator</div></a>\n      <a href=\"/calculators/baby/baby-name-popularity-calculator\" class=\"calc-card\"><div class=\"calc-card-icon\">⭐</div><div class=\"calc-card-name\">Baby Name Popularity</div></a>\n    </div>\n  </div>\n</section>\n</main>" }} />
    </>
  );
}
